// Code generation for @synfin/spec.
//
// JSON Schema (schemas/*.schema.json) is the single source of truth for the
// off-ledger SQSS wire types (SPECIFICATION.md §4). This script regenerates two
// committed artifacts from those schemas:
//
//   1. src/generated/types.ts   — TypeScript types (json-schema-to-typescript)
//   2. src/generated/schemas.ts — the schema objects as a TS module, so the
//      runtime validators compile them without relying on JSON import
//      attributes (portable across Node, vitest and the build).
//
// Run `node scripts/gen.mjs` to regenerate; `node scripts/gen.mjs --check`
// fails if the committed output is out of date (used by CI, ENGINEERING.md §8).

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import * as prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const repoRoot = resolve(pkgRoot, '..', '..');
const schemasDir = join(pkgRoot, 'schemas');
const generatedDir = join(pkgRoot, 'src', 'generated');

const BANNER =
  '/* eslint-disable */\n' +
  '// AUTO-GENERATED by scripts/gen.mjs from schemas/*.schema.json — DO NOT EDIT.\n' +
  '// Run `pnpm --filter @synfin/spec gen` to regenerate. CI fails on drift.\n';

// Stable order: primitives first, then wire types. Drives deterministic output.
const WIRE_FILES = [
  ['swap-intent.schema.json', 'SwapIntent', 'swapIntentSchema'],
  [
    'intent-constraints.schema.json',
    'IntentConstraints',
    'intentConstraintsSchema',
  ],
  ['quote-request.schema.json', 'QuoteRequest', 'quoteRequestSchema'],
  ['quote.schema.json', 'Quote', 'quoteSchema'],
  ['route-plan.schema.json', 'RoutePlan', 'routePlanSchema'],
  ['route-leg.schema.json', 'RouteLeg', 'routeLegSchema'],
];

function readSchema(file) {
  return JSON.parse(readFileSync(join(schemasDir, file), 'utf8'));
}

// Map a cross-file $ref (used in the standalone schema files) onto a local
// pointer inside the bundled document used for type generation.
function rewriteRef(ref) {
  if (ref.startsWith('primitives.schema.json#')) {
    return ref.replace('primitives.schema.json#', '#');
  }
  const def = WIRE_FILES.find(([file]) => file === ref);
  if (def) return `#/$defs/${def[1]}`;
  return ref;
}

function rewriteRefsDeep(node) {
  if (Array.isArray(node)) return node.map(rewriteRefsDeep);
  if (node && typeof node === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === '$ref' && typeof v === 'string') out[k] = rewriteRef(v);
      else out[k] = rewriteRefsDeep(v);
    }
    return out;
  }
  return node;
}

function stripMeta(schema) {
  // Remove document-level keywords that do not belong inside a $defs entry, and
  // the conditional keywords (allOf/if/then/else). The conditionals encode
  // runtime validation rules (e.g. firm quotes require commitment+signature)
  // that the *structural* TypeScript type cannot express; they remain in the
  // runtime schema module (schemas.ts) so Ajv still enforces them.
  const {
    $schema,
    $id,
    allOf,
    if: _if,
    then: _then,
    else: _else,
    ...rest
  } = schema;
  void $schema;
  void $id;
  void allOf;
  void _if;
  void _then;
  void _else;
  return rest;
}

async function buildTypes() {
  const primitives = readSchema('primitives.schema.json');
  const $defs = { ...rewriteRefsDeep(primitives.$defs) };
  const rootProps = {};
  for (const [file, title] of WIRE_FILES) {
    const schema = rewriteRefsDeep(stripMeta(readSchema(file)));
    $defs[title] = schema;
    rootProps[title] = { $ref: `#/$defs/${title}` };
  }
  // A root that references every wire type so all are reachable (and thus
  // emitted) by json-schema-to-typescript.
  const bundle = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'SqssTypeIndex',
    description:
      'Index of all SQSS wire types (generated). Prefer importing the named types directly.',
    type: 'object',
    additionalProperties: false,
    properties: rootProps,
    $defs,
  };
  const ts = await compile(bundle, 'SqssTypeIndex', {
    bannerComment: '',
    additionalProperties: false, // clean interfaces (no index signatures)
    declareExternallyReferenced: true,
    enableConstEnums: false,
    format: false,
    cwd: schemasDir,
  });
  return ts;
}

function buildSchemasModule() {
  const entries = [
    ['primitivesSchema', 'primitives.schema.json'],
    ...WIRE_FILES.map(([file, , constName]) => [constName, file]),
  ];
  const lines = [];
  const names = [];
  for (const [name, file] of entries) {
    const schema = readSchema(file);
    lines.push(
      `export const ${name}: Record<string, unknown> = ${JSON.stringify(schema)};`,
    );
    names.push(name);
  }
  lines.push('');
  lines.push(
    `export const allSchemas: Record<string, unknown>[] = [${names.join(', ')}];`,
  );
  return lines.join('\n') + '\n';
}

async function format(code, parser) {
  const config = (await prettier.resolveConfig(repoRoot)) ?? {};
  return prettier.format(code, { ...config, parser });
}

async function main() {
  const check = process.argv.includes('--check');

  const typesCode = await format(
    BANNER + '\n' + (await buildTypes()),
    'typescript',
  );
  const schemasCode = await format(
    BANNER + '\n' + buildSchemasModule(),
    'typescript',
  );

  const targets = [
    [join(generatedDir, 'types.ts'), typesCode],
    [join(generatedDir, 'schemas.ts'), schemasCode],
  ];

  if (check) {
    let drift = false;
    for (const [path, code] of targets) {
      let current = '';
      try {
        current = readFileSync(path, 'utf8');
      } catch {
        current = '';
      }
      if (current !== code) {
        drift = true;
        console.error(`Generated file out of date: ${path}`);
      }
    }
    if (drift) {
      console.error(
        'Run `pnpm --filter @synfin/spec gen` and commit the result.',
      );
      process.exit(1);
    }
    console.log('Generated types are in sync.');
    return;
  }

  // Best-effort guard so a stray manual file in schemas/ does not silently drop.
  const present = readdirSync(schemasDir).filter((f) =>
    f.endsWith('.schema.json'),
  );
  const known = new Set([
    'primitives.schema.json',
    ...WIRE_FILES.map(([f]) => f),
  ]);
  for (const f of present) {
    if (!known.has(f)) {
      throw new Error(
        `Unknown schema file ${f}; add it to WIRE_FILES in scripts/gen.mjs.`,
      );
    }
  }

  mkdirSync(generatedDir, { recursive: true });
  for (const [path, code] of targets) writeFileSync(path, code);
  console.log('Generated src/generated/types.ts and src/generated/schemas.ts');
}

await main();
